---
title: "Markdown"
author: "Josh Somoukian and Thomas Pepperz"
date: "`r Sys.Date()`"
classoption: landscape
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readr)
library(lubridate)
library(knitr)
library(data.table)

#Importing data
assignments = read_csv("~/R/unspecified-ML-project/ML Project/assignments.csv", 
                        col_types = cols(assignment_created_at = col_datetime(format = "%Y-%m-%d %H:%M:%S"), 
                                         start_date = col_datetime(format = "%Y-%m-%d %H:%M:%S"), 
                                         end_date = col_datetime(format = "%Y-%m-%d %H:%M:%S"), 
                                         filled_date = col_datetime(format = "%Y-%m-%d %H:%M:%S"), 
                                         hours_worked = col_double(),
                                         bonus_percent = col_double(),
                                         admin_bonus_percent = col_double(),
                                         bonus_added_at = col_datetime(format = "%Y-%m-%d %H:%M:%S"),
                                         professional_removed_at = col_datetime(format = "%Y-%m-%d %H:%M:%S")))

contractor_availability_true = read_csv("~/R/unspecified-ML-project/ML Project/contractor-availability-true.csv", 
                                        col_types = cols(date = col_date(format = "%Y-%m-%d")))

contractor_geolocations_distance = read.csv('~/R/unspecified-ML-project/ML Project/contractor-geolocations-distance.csv')

office_alternative_locations = read.csv('~/R/unspecified-ML-project/ML Project/office-alternative-locations.csv')

office_geolocations = read.csv('~/R/unspecified-ML-project/ML Project/offices-geolocations-wcity.csv')

office_softwares = read.csv('~/R/unspecified-ML-project/ML Project/office-softwares.csv')

assignment_supply = fread("~/R/unspecified-ML-project/Output/assignment-supply.csv")

#Categorizing assignments into Morning/Afternoon/Evening/Overnight. Also creating columns that return the difference between various date columns in hours
assignments = assignments %>%
  mutate(
    time_of_day = case_when(
      hour(start_date) >= 5 & hour(start_date) < 11 ~ 'Morning',
      hour(start_date) >= 11 & hour(start_date) < 17 ~ 'Afternoon',
      hour(start_date) >= 17 & hour(start_date) < 23 ~ 'Evening',
      hour(start_date) >= 23 | hour(start_date) < 5 ~ 'Overnight'
    ),
    is_filled = case_when(
      is.na(filled_date) ~ 0,
      T ~ 1
    ),
    time_to_fill = difftime(filled_date, assignment_created_at, units = "hours"),
    length_of_assignment = difftime(end_date, start_date, units = "hours"),
    time_to_start = difftime(start_date, assignment_created_at, units = "hours")
  )

#Replace NA values in the bonus percent column with 0's for grouping and calclulating purposes
assignments$bonus_percent = replace_na(assignments$bonus_percent, 0)

#For now, cutting off assignments that have a start date more than 3 months from today's date because many of those are unfilled
assignments = assignments %>%
  filter(start_date <= (Sys.Date() + 90))

#Remove negative values for length of assignment
assignments = assignments %>%
  filter(length_of_assignment > 0)
```

# Summary Statistics

## Fill Rate

```{r summary stats, echo=F, warning=F}
assignments %>%
  group_by(time_of_day) %>%
  summarize(
    "Fill Rate" = mean(is_filled,
                       na.rm = T),
    "Assignments Filled" = sum(is_filled),
    "Assignments Unfilled" = sum(is_filled == 0)
  ) %>%
  rbind(
    assignments %>%
  group_by(is_filled) %>%
  summarize(
    "Fill Rate" = mean(is_filled,
                       na.rm = T),
    "Assignments Filled" = sum(is_filled),
    "Assignments Unfilled" = sum(is_filled == 0)
  ) %>%
    rename(time_of_day = is_filled),
    assignments %>%
  summarize(
    time_of_day = "ALL",
    "Fill Rate" = mean(is_filled,
                       na.rm = T),
    "Assignments Filled" = sum(is_filled),
    "Assignments Unfilled" = sum(is_filled == 0)
    )
  ) %>%
  rename(Group = time_of_day) %>%
  mutate(Group = replace(Group, 
                         Group == 0, 
                         "Not Filled"),
         Group = replace(Group,
                         Group == 1,
                         "Filled")) %>%
  kable()
```

## Post to Fill

```{r, echo=F, warning=F}
assignments %>%
  group_by(time_of_day) %>%
  summarize(
    "Average Post to Fill" = mean(time_to_fill,
                                  na.rm = T),
    "SD Post to Fill" = sd(time_to_fill,
                           na.rm = T),
    "Min Post to Fill" = min(time_to_fill,
                             na.rm = T),
    "Median Post to Fill" = median(time_to_fill,
                                   na.rm = T),
    "Max Post to Fill" = max(time_to_fill,
                             na.rm = T)
  ) %>%
  rbind(
    assignments %>%
  group_by(is_filled) %>%
  summarize(
    "Average Post to Fill" = mean(time_to_fill,
                                  na.rm = T),
    "SD Post to Fill" = sd(time_to_fill,
                           na.rm = T),
    "Min Post to Fill" = min(time_to_fill,
                             na.rm = T),
    "Median Post to Fill" = median(time_to_fill,
                                   na.rm = T),
    "Max Post to Fill" = max(time_to_fill,
                             na.rm = T)
  ) %>%
    rename(time_of_day = is_filled),
    assignments %>%
  summarize(
    time_of_day = "ALL",
    "Average Post to Fill" = mean(time_to_fill,
                                  na.rm = T),
    "SD Post to Fill" = sd(time_to_fill,
                           na.rm = T),
    "Min Post to Fill" = min(time_to_fill,
                             na.rm = T),
    "Median Post to Fill" = median(time_to_fill,
                                   na.rm = T),
    "Max Post to Fill" = max(time_to_fill,
                             na.rm = T)
    )
  ) %>%
  rename(Group = time_of_day) %>%
  mutate(Group = replace(Group, 
                         Group == 0, 
                         "Not Filled"),
         Group = replace(Group,
                         Group == 1,
                         "Filled")) %>%
  kable()
```

\newpage
## Post to Start

```{r, echo=F, warning=F}
assignments %>%
  group_by(time_of_day) %>%
  summarize(
    "Average Post to Start" = mean(time_to_start,
                                   na.rm = T),
    "SD Post to Start" = sd(time_to_start,
                            na.rm = T),
    "Min Post to Start" = min(time_to_start,
                              na.rm = T),
    "Median Post to Start" = median(time_to_start,
                                    na.rm = T),
    "Max Post to Start" = max(time_to_start,
                              na.rm = T)
  ) %>%
  rbind(
    assignments %>%
  group_by(is_filled) %>%
  summarize(
    "Average Post to Start" = mean(time_to_start,
                                   na.rm = T),
    "SD Post to Start" = sd(time_to_start,
                            na.rm = T),
    "Min Post to Start" = min(time_to_start,
                              na.rm = T),
    "Median Post to Start" = median(time_to_start,
                                    na.rm = T),
    "Max Post to Start" = max(time_to_start,
                              na.rm = T)
  ) %>%
    rename(time_of_day = is_filled),
    assignments %>%
  summarize(
    time_of_day = "ALL",
    "Average Post to Start" = mean(time_to_start,
                                   na.rm = T),
    "SD Post to Start" = sd(time_to_start,
                            na.rm = T),
    "Min Post to Start" = min(time_to_start,
                              na.rm = T),
    "Median Post to Start" = median(time_to_start,
                                    na.rm = T),
    "Max Post to Start" = max(time_to_start,
                              na.rm = T)
    )
  ) %>%
  rename(Group = time_of_day) %>%
  mutate(Group = replace(Group, 
                         Group == 0, 
                         "Not Filled"),
         Group = replace(Group,
                         Group == 1,
                         "Filled")) %>%
  kable()
```

## Bonus Analysis
``` {r bonus, echo=F, warning=F}
assignments %>%
  group_by(bonus_percent) %>%
  summarise(
    "Postings Filled" = sum(is_filled),
    "Total Postings" = n(),
    "Fill Rate" = round(sum(is_filled)/n(), digits = 3),
    "Median Assignment Length" = median(length_of_assignment,
                                   na.rm = T),
    "Median Time to Fill" = median(time_to_fill,
                                   na.rm = T),
    "Median Time to Start" = median(time_to_start,
                                    na.rm = T)
      ) %>% 
  rbind(
    assignments %>%
      filter(bonus_percent > 0) %>%
      summarise(
        bonus_percent = "Any Bonus",
        "Postings Filled" = sum(is_filled),
        "Total Postings" = n(),
        "Fill Rate" = round(sum(is_filled)/n(), digits = 3),
        "Median Assignment Length" = median(length_of_assignment,
                                            na.rm = T),
        "Median Time to Fill" = median(time_to_fill,
                                       na.rm = T),
        "Median Time to Start" = median(time_to_start,
                                        na.rm = T)
      )
  ) %>%
  kable()
```